관리자 모드 개선 및 https 변환 메뉴 추가, workflow 추가
gnuboard/gnuboard5 pull request #239
Opened 2023-06-15 19:55 UTC by sooobee

안녕하세요. 전북대학교 컴퓨터인공지능학부 4학년 공리, 권시은, 박진용, 김수비 입니다. 

오픈소스에 기여해야하는 학교 과제로 인해 그누보드를 직접 사용해보고 다음과 같은 부분을 개선하면 사용자에게 더욱 편리할 것 같아 부족한 걸 알지만 최대한 수정을 진행해 보았습니다.

1. 관리자 모드 1:1 문의 설정(qa_config.php) 창에서 확인 버튼을 저장과 목록 버튼으로 분리

2. 관리자 모드 메뉴 설정에서 메뉴 다중 선택 가능하도록 변경

3. http 보안 강화를 위한 설명 메뉴 추가

4. CI를 위한 workflow 추가 (push시 설정 php 버전과의 호환성 체크) 

감사합니다.

2023-06-19 15:52 UTC, smaker commented
@kkigomi 님이 제기한 문제 이외에 좀 더 더하자면,

.htaccess 파일의 내용을 변경하고 있는데, 해당 파일에 쓰기 권한이 없어서 해당 동작이 실패할 수도 있습니다.
이 부분에 대한 보완도 필요할 것 같습니다.

2023-08-10 10:44 UTC, enkhjargal requested changes

2023-08-10 10:44 UTC, enkhjargal commented on adm/security.php
> +    </h1>
```suggestion
    <h1>HTTP를 HTTPS로 바꾸기 위해서는 SSL인증서가 필요합니다.</h1>
```

2023-08-10 10:44 UTC, enkhjargal commented on plugin/PHPMailer/docs/Callback_function_notes.txt
> +Please review the  script for the example.
```suggestion
Please review the script for the example.
```

2023-12-18 06:57 UTC, thisgun commented
안녕하세요. SIR 입니다.

코드를 남겨주셔서 감사합니다.

앞으로 개발 하는데 참고하겠습니다.

2026-06-30 00:55 UTC, closed without merging